### ISSUE TITLE
LCA tsv

### ISSUE THREAD

**Issue by lauramilena3** [soedinglab/spacepharer#2]
Dear spacepharer developers, 

Great tool! I have been testing it today with an assembly of a viral metagenome. I ran these two commands with the latest github version:

spacepharer downloaddb spacers_shmakov_et_al_2017 shmakovSetDB tmpFolder
spacepharer predictmatch shmakovSetDB viralTargetDB viralTargetDB_rev spacepharer_shmakov.tsv tmpFolder

## Expected Behavior

I was expecting a file with the suffix _lca.tsv with the taxonomy of each spacer.

## Current Behavior

I got a file with lca_per_target.tsv suffix. It is giving me the taxonomy of the viruses (Although the viral database was not created with taxonomic labels)

## Your Environment
* Git commit used:  2.fc5e668, self-compiled

Tak!

**Comment by RuoshiZhang** [comment]
If you provide viral database only and download spacers db (which includes the tax labels), you should expect a "lca_per_target.tsv", which gives you the taxonomy of _host_ LCA for each virus. The "lca.tsv" file is only created when you provide viral taxonomic labels, and the file contains the taxonomy of the matched _virus_ LCA for each spacer. I realized this is not very clear in the README, I will try to improve it somehow.

We have just integrated MMseqs2 taxonomy recently, and we will make a new release very soon.

**Comment by RuoshiZhang** [comment]
I just found out that the description in README was wrong about which database will give you which file ("The SpacePHARER output" section). I just corrected it. Sorry for the confusion.
