### ISSUE TITLE
predictmatch/findpam fail

### ISSUE THREAD

**Issue by GeoMicroSoares** [soedinglab/spacepharer#4]
## Expected Behavior
Running `spacepharer easy-predict`.
## Current Behavior
Errors out with

## Steps to Reproduce (for bugs)
`$ spacepharer easy-predict ../FASTA/* spacepharer/targetSetDB predictions.tsv tmpFolder --threads 8`

## Spacepharer Output (for bugs)

```
predictmatch tmpFolder/7987378095363681824/qsetdb spacepharer/targetSetDB spacepharer/targetSetDB_rev predictions.tsv tmpFolder/7987378095363681824/predict --threads 8 --db-output 0

findpam spacepharer/targetSetDB_nucl tmpFolder/7987378095363681824/predict/1110362888042562515/aln_merge tmpFolder/7987378095363681824/predict/1110362888042562515/aln_merge_pam --flanking-seq-len 10 --compressed 0 --threads 8 -v 3

tmpFolder/7987378095363681824/predict/1110362888042562515/predictmatch.sh: line 164: 28594 Bus error: 10           "${MMSEQS}" findpam "${TARGET}_nucl" "${TMP_PATH}/aln_merge" "${TMP_PATH}/aln_merge_pam" ${FINDPAM_PAR}
Error: findpam failed
Error: predictmatch failed
```

## Context
Built a `spacepharer` database (and a reverse one) based on high- and medium-quality viral genomes (checkV) as follows:

```
spacepharer createsetdb ../checkv_out/h_m_quality_viruses_clean.fna targetSetDB tmpFolder
spacepharer createsetdb ../checkv_out/h_m_quality_viruses_clean.fna targetSetDB_rev tmpFolder --reverse-fragments 1
```

Then used it on bacterial MAGs (anvi'o), as such, which caused the error:

```
spacepharer easy-predict ../SGG_PILECR/FASTA/* spacepharer/targetSetDB predictions.tsv tmpFolder --threads 8
```

## Your Environment

Running a MacOS BigSur 11.2.3 (M1, 16GB RAM), installed with `conda install -c conda-forge -c bioconda spacepharer`.

Please let me know if you need any other information on this. Thanks!

**Comment by GeoMicroSoares** [comment]
Using `--report-pam 0` runs the whole pipeline to completion, but not sure if this would be the right way...

**Comment by milot-mirdita** [comment]
I am not 100% sure how to debug the issue. Try something like the following:

1) Check if lldb is installed with `lldb -v`. If not install the macOS command line tools with `xcode-select --install`.
2) Run the crashing command inside lldb:
```
# cd to the same directory as before
lldb -- spacepharer findpam spacepharer/targetSetDB_nucl tmpFolder/7987378095363681824/predict/1110362888042562515/aln_merge tmpFolder/7987378095363681824/predict/1110362888042562515/aln_merge_pam --flanking-seq-len 10 --compressed 0 --threads 8 -v 3
```
3) Wait for a prompt and add a bunch of additional breakpoints:
```
b abort
b exit
b _exit
```
4) Run the binary with `r` (for run) and press enter.
5) Wait for the crash or exit, once you are back at a prompt. Enter `bt` (for backtrace) and press enter.
6) Copy the output and paste it here.

Alternatively please upload all these files:
```
spacepharer/targetSetDB_nucl*
tmpFolder/7987378095363681824/predict/1110362888042562515/aln_merge*
```

E.g. with
```
tar czvf debug.tar.gz spacepharer/targetSetDB_nucl* tmpFolder/7987378095363681824/predict/1110362888042562515/aln_merge*
```

A smaller archive created with the following command should also work (though not 100% sure about this):
```
tar czvf debug.tar.gz spacepharer/targetSetDB_nucl{,.index,.dbtype,_set_to_contig,_set_to_contig.index,_set_to_contig.dbtype} tmpFolder/7987378095363681824/predict/1110362888042562515/aln_merge.[0-9]* tmpFolder/7987378095363681824/predict/1110362888042562515/aln_merge{,.dbtype,.index}
```
Send this archive to us so we can try to find out what exactly is crashing.

By the way, the binaries at https://mmseqs.com/spacepharer/ contain a native build for the M1 (which doesn't run through rosetta2 and should be faster, and also maybe won't crash(??)). Bioconda doesn't have native support for the M1 yet.

**Comment by milot-mirdita** [comment]
Could you try the latest build from https://mmseqs.com/spacepharer/? I hope we solved the issue yesterday.
