### ISSUE TITLE
spacepharer downloaddb error

### ISSUE THREAD

**Issue by snayfach** [soedinglab/spacepharer#6]
I've installed the latest version available in conda but running into an error here:

`$ spacepharer downloaddb GenBank_phage_2018_09 querySetDB tmpFolder`

> Create directory tmpFolder
> downloaddb GenBank_phage_2018_09 querySetDB tmpFolder
> 
> MMseqs Version:      	4.228b9e5
> Create reversed setdb	1
> Threads              	64
> Verbosity            	3
> 
> 2021-04-19 19:38:22 URL:http://wwwuser.gwdg.de/~compbiol/spacepharer/2018_09/genbank_phages_2018_09.tar [144250880/144250880] -> "genbank_phages_2018_09.tar" [1]
> 2021-04-19 19:38:23 URL:http://wwwuser.gwdg.de/~compbiol/spacepharer/2018_09/genbank_phages_2018_09.tsv [405478/405478] -> "genbank_phages_2018_09.tsv" [1]
> tmpFolder/4509843044695086851/downloadb.sh: line 121: /global/projectb/scratch/snayfach/projects/checkv-db/9_crispr/2_spacepharer/spacepharer: No such file or directory
> Error: tar2db failedoutput.

**Comment by milot-mirdita** [comment]
Could you execute these two commands:
```
ls -la /global/projectb/scratch/snayfach/projects/checkv-db/9_crispr/2_spacepharer/spacepharer

echo $PATH
```

for some reason spacepharer cannot find its own binary anymore during execution? Also it seems to use a binary that doesn’t come from conda?

**Comment by snayfach** [comment]
`$ ls -la /global/projectb/scratch/snayfach/projects/checkv-db/9_crispr/2_spacepharer/spacepharer`

> ls: cannot access '/global/projectb/scratch/snayfach/projects/checkv-db/9_crispr/2_spacepharer/spacepharer': No such file or directory

`$ echo $PATH`

> /global/homes/s/snayfach/.conda/envs/spacepharer/bin:/usr/common/software/python/3.8-anaconda-2020.11/condabin:/usr/common/software/python/3.8-anaconda-2020.11/bin:/global/homes/s/snayfach/.local/cori/3.8-anaconda-2020.11/bin:/opt/cray/pe/mpt/7.7.10/gni/bin:/opt/cray/rca/2.2.20-7.0.1.1_4.61__g8e3fb5b.ari/bin:/opt/cray/alps/6.6.58-7.0.1.1_6.19__g437d88db.ari/sbin:/opt/cray/alps/default/bin:/opt/cray/job/2.2.4-7.0.1.1_3.47__g36b56f4.ari/bin:/opt/cray/pe/craype/2.6.2/bin:/opt/intel/compilers_and_libraries_2019.3.199/linux/bin/intel64:/usr/common/software/darshan/3.2.1/bin:/global/common/cori/software/altd/2.0/bin:/usr/common/software/bin:/usr/common/nsg/bin:/opt/ovis/bin:/opt/ovis/sbin:/opt/cray/pe/modules/3.2.11.4/bin:/usr/local/bin:/usr/bin:/bin:/usr/lib/mit/bin:/usr/lib/mit/sbin:/opt/cray/pe/bin

**Comment by milot-mirdita** [comment]
I think I found the issue. We will make a new release as soon as we fix some other open issues.

**Comment by snayfach** [comment]
Thanks!

**Comment by milot-mirdita** [comment]
I forgot to update you, we made a new release and `downloaddb` should work correctly now.
