### ISSUE TITLE
Predictmatch failed

### ISSUE THREAD

**Issue by susheelbhanu** [soedinglab/spacepharer#8]
## Current Behavior
```
Error: predictmatch failed
```

## Steps to Reproduce (for bugs)
Running spacepharer as follows:
```
mkdir -p /work/projects/nomis/assemblies/virome_results/tmp/spacepharer/GFS_7449 && spacepharer easy-predict /work/projects/nomis/assemblies/virome_results/minced/GFS_7449.txt /work/projects/nomis/assemblies/virome_results/spacepharer/targetSetDB /work/projects/nomis/assemblies/virome_results/spacepharer/GFS_7449/spacepharer_predictions.tsv /work/projects/nomis/assemblies/virome_results/tmp/spacepharer/GFS_7449 --threads 6 --remove-tmp-files --fmt 0
```

## Spacepharer Output (for bugs)
See attached file.

## Context
Providing context helps us come up with a solution and improve our documentation for the future.
[Uploading spacepharer.GFS_7449.log.txt…]()

Thanks for your help!

**Comment by milot-mirdita** [comment]
The log file didn’t seem to have uploaded correctly, can you please upload it again?

**Comment by susheelbhanu** [comment]
[spacepharer.GFS_7449.log.txt](https://github.com/soedinglab/spacepharer/files/9483035/spacepharer.GFS_7449.log.txt)

Hope this works. Thanks for the help!

**Comment by milot-mirdita** [comment]
It failed at the very end, during the cleanup stage. The result files that were produced should be complete. Not sure why the cleanup failed though

**Comment by susheelbhanu** [comment]
I'm running it in a snakemake workflow and unforunately, because of that it likely removes the output file... Any recommendations? Just remove the --remove-tmp flag?

**Comment by milot-mirdita** [comment]
That should work, you can manually remove the tmp folder in your workflow instead

**Comment by susheelbhanu** [comment]
Great, thank you

**Comment by susheelbhanu** [comment]
@milot-mirdita Two questions:

1. I have some samples that seem to finish without errors. However, the `predictions.tsv` file is empty. Is this expected behaviour?
2. Other samples seem to be having `segmentation fault`. The log file is attached. 
[spacepharer.GFS_10588.txt](https://github.com/soedinglab/spacepharer/files/9483368/spacepharer.GFS_10588.txt)

I check the `memory usage` on these samples and it looks alright even.
```
Job ID: 2910398
Cluster: iris
User/Group: sbusi/clusterusers
State: FAILED (exit code 1)
Nodes: 1
Cores per node: 6
CPU Utilized: 00:00:03
CPU Efficiency: 16.67% of 00:00:18 core-walltime
Job Wall-clock time: 00:00:03
Memory Utilized: 0.00 MB (estimated maximum)
Memory Efficiency: 0.00% of 158.20 GB (26.37 GB/core)
```

**Comment by RuoshiZhang** [comment]
`predictions.tsv` in theory can be empty if there isn't enough evidence (controlled by the null model) to report a match.
The second issue seems to be caused by giving an empty MinCED file. 
For both cases, could you please upload one of the MinCED output files so we can try to reproduce it locally?

**Comment by susheelbhanu** [comment]
Thank you. Attached the minced output for both cases.

[GFS_7449_spacers.fa.txt](https://github.com/soedinglab/spacepharer/files/9483726/GFS_7449_spacers.fa.txt)
[GFS_7449.txt](https://github.com/soedinglab/spacepharer/files/9483727/GFS_7449.txt)
[GFS_10588_spacers.fa.txt](https://github.com/soedinglab/spacepharer/files/9483728/GFS_10588_spacers.fa.txt)
[GFS_10588.txt](https://github.com/soedinglab/spacepharer/files/9483729/GFS_10588.txt)

**Comment by RuoshiZhang** [comment]
I fixed the issue with `--remove-tmp-files` throwing an error. 
The seg fault was indeed cause by all input files being empty, and no spacer sequences could be extracted. This case should now be handled better by `parsespacer`.
Is there any particular reason for running `easy-predict` with only one input file at a time? `easy-predict` can take multiple spacer files as input, which could actually help create a better baseline than using a single set of spacers.

**Comment by susheelbhanu** [comment]
@RuoshiZhang Thank you for fixing the issue. I can confirm that the earlier approach, i.e. removed the tmp folder manually, does the trick. 

The idea in this case was to use `easy-predict` to input compare each `bacterial mag` against a dereplicated set of `viral mags` to identify which may be linked. 

For example, we have 14K bacterial mags that we ran `minced` on individually. Would you suggest that we provide all of minced's output? Open to suggestions.

Thank you!

**Comment by RuoshiZhang** [comment]
Yes, in this case I would recommend giving all the bacterial mags' spacer files together in one search. The scores for each set of spacers are computed individually against the viral database, and the null model is larger so the FDR estimation is more accurate. All the host-virus matches below the FDR threshold are reported in the output file. It should also save quite a bit of runtime.

**Comment by susheelbhanu** [comment]
Great, will try that. Thank you!!

P.S. Feel free to close the issue :)

**Comment by susheelbhanu** [comment]
@RuoshiZhang I have a stupid question, but to provide the spacer files for all of the bacterial mags, will a comma separated list do or is it better if we concatenate all the spacer information into a single file?

Thank you for your help!

**Comment by RuoshiZhang** [comment]
@susheelbhanu the file names should be separated by spaces like individual arguments, or you can use the wildcard symbol (like `examples/*.fas`) to expand.

**Comment by susheelbhanu** [comment]
Perfect, thank you!

So, something like this?

```
spacepharer easy-predict CRISPR1.txt CRISPR2.txt CRISPR3.txt {input. DB} {output} {params.TMPDIR} --threads {threads} --fmt 0 --report-pam 0
```

**Comment by RuoshiZhang** [comment]
Yes, that should work

> Perfect, thank you!
> 
> So, something like this?
> 
> ```
> spacepharer easy-predict CRISPR1.txt CRISPR2.txt CRISPR3.txt {input. DB} {output} {params.TMPDIR} --threads {threads} --fmt 0 --report-pam 0
> ```
