### ISSUE TITLE
Question regarding score cutoff

### ISSUE THREAD

**Issue by susheelbhanu** [soedinglab/spacepharer#9]
Hi @RuoshiZhang, 

I successfully ran `spacepharer`, so thank you for the earlier input. I now have a question regarding what is a potential cutoff or how one could interpret the scores in the `predictions.csv` file from the `--fmt 0` option.

Below is an example of some of the scores and hits that I am getting:
```
#GL72_DN_concoct_217.txt        S47CGL_R68_GL53_UP_2_contig133229       1.195E+02       11
#GL16_Down_metabinner_11.txt    S99CGL_16_Down_contig140817     1.166E+01       1
#GL116_DN_concoct_233.txt       S168CGL116_DN_contig90642       1.816E+02       7
#GL50_Down_metabinner_33_sub.txt        S149CGL50_UP_contig138377       7.610E+01       7
#GFS_9203.txt   S61CGL_R56_GL46_UP_1_contig30026        4.622E+01       4
#GL51_Up_metabinner_2.txt       S111CGL24_UP_contig148088       1.106E+01       2
#340R_metabinner_16_sub.txt     S140C340R_contig127757  5.266E+01       3
#GL102_DN_metabinner_13_sub.txt S35CGL28_DN_contig133789        1.379E+02       8
#GL122_UP_metabinner_5.txt      S177CGL122_UP_contig169282      2.726E+02       35
#GL124_UP_metabinner_16.txt     S178CGL124_UP_contig_233335     8.730E+02       30
```

While I understand the number of hits, is there a potential score cutoff that one can use to eliminate putatively false predictions?

Thank you!

**Comment by RuoshiZhang** [comment]
The phage-host pairs are selected based on false discovery rate (by default 0.05), while the scores can only be used for ranking the pairs on the strength of evidence. Only pairs with scores above certain threshold calculated from the given FDR cutoff will be presented in the output. You could change the `--fdr` parameter to get more or fewer result, but there is no universal score cutoff.

**Comment by susheelbhanu** [comment]
Okay, thank you. I suppose it makes sense that the data is already filtered based on FDR values.
